// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: controlplane/v1/controlplane.proto

package controlplanev1

import (
	v1 "github.com/gulyaev-iv/go-cloud-des/api/dispatcher/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitExperimentBatchRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	BatchId         string                  `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Dsl             string                  `protobuf:"bytes,2,opt,name=dsl,proto3" json:"dsl,omitempty"`
	StoreSource     bool                    `protobuf:"varint,3,opt,name=store_source,json=storeSource,proto3" json:"store_source,omitempty"`
	StoreBinary     bool                    `protobuf:"varint,4,opt,name=store_binary,json=storeBinary,proto3" json:"store_binary,omitempty"`
	BuildTimeoutSec int32                   `protobuf:"varint,5,opt,name=build_timeout_sec,json=buildTimeoutSec,proto3" json:"build_timeout_sec,omitempty"`
	Common          *ExperimentCommonConfig `protobuf:"bytes,6,opt,name=common,proto3" json:"common,omitempty"`
	Experiments     []*ExperimentParams     `protobuf:"bytes,7,rep,name=experiments,proto3" json:"experiments,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitExperimentBatchRequest) Reset() {
	*x = SubmitExperimentBatchRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitExperimentBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitExperimentBatchRequest) ProtoMessage() {}

func (x *SubmitExperimentBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitExperimentBatchRequest.ProtoReflect.Descriptor instead.
func (*SubmitExperimentBatchRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitExperimentBatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *SubmitExperimentBatchRequest) GetDsl() string {
	if x != nil {
		return x.Dsl
	}
	return ""
}

func (x *SubmitExperimentBatchRequest) GetStoreSource() bool {
	if x != nil {
		return x.StoreSource
	}
	return false
}

func (x *SubmitExperimentBatchRequest) GetStoreBinary() bool {
	if x != nil {
		return x.StoreBinary
	}
	return false
}

func (x *SubmitExperimentBatchRequest) GetBuildTimeoutSec() int32 {
	if x != nil {
		return x.BuildTimeoutSec
	}
	return 0
}

func (x *SubmitExperimentBatchRequest) GetCommon() *ExperimentCommonConfig {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *SubmitExperimentBatchRequest) GetExperiments() []*ExperimentParams {
	if x != nil {
		return x.Experiments
	}
	return nil
}

type ExperimentCommonConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StopRule         *v1.StopRule           `protobuf:"bytes,1,opt,name=stop_rule,json=stopRule,proto3" json:"stop_rule,omitempty"`
	Metrics          []string               `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	MetricStep       float64                `protobuf:"fixed64,3,opt,name=metric_step,json=metricStep,proto3" json:"metric_step,omitempty"`
	StoreMetrics     bool                   `protobuf:"varint,4,opt,name=store_metrics,json=storeMetrics,proto3" json:"store_metrics,omitempty"`
	MemoryLimitBytes uint64                 `protobuf:"varint,5,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	RunTimeoutMs     uint64                 `protobuf:"varint,6,opt,name=run_timeout_ms,json=runTimeoutMs,proto3" json:"run_timeout_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExperimentCommonConfig) Reset() {
	*x = ExperimentCommonConfig{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentCommonConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentCommonConfig) ProtoMessage() {}

func (x *ExperimentCommonConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentCommonConfig.ProtoReflect.Descriptor instead.
func (*ExperimentCommonConfig) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *ExperimentCommonConfig) GetStopRule() *v1.StopRule {
	if x != nil {
		return x.StopRule
	}
	return nil
}

func (x *ExperimentCommonConfig) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ExperimentCommonConfig) GetMetricStep() float64 {
	if x != nil {
		return x.MetricStep
	}
	return 0
}

func (x *ExperimentCommonConfig) GetStoreMetrics() bool {
	if x != nil {
		return x.StoreMetrics
	}
	return false
}

func (x *ExperimentCommonConfig) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ExperimentCommonConfig) GetRunTimeoutMs() uint64 {
	if x != nil {
		return x.RunTimeoutMs
	}
	return 0
}

type ExperimentParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExperimentId  string                 `protobuf:"bytes,1,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	SetVars       []*v1.SetVar           `protobuf:"bytes,2,rep,name=set_vars,json=setVars,proto3" json:"set_vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentParams) Reset() {
	*x = ExperimentParams{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentParams) ProtoMessage() {}

func (x *ExperimentParams) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentParams.ProtoReflect.Descriptor instead.
func (*ExperimentParams) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *ExperimentParams) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *ExperimentParams) GetSetVars() []*v1.SetVar {
	if x != nil {
		return x.SetVars
	}
	return nil
}

type SubmitExperimentBatchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accepted       bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	BatchId        string                 `protobuf:"bytes,2,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	ModelHash      string                 `protobuf:"bytes,3,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	SelectedGoos   string                 `protobuf:"bytes,5,opt,name=selected_goos,json=selectedGoos,proto3" json:"selected_goos,omitempty"`
	SelectedGoarch string                 `protobuf:"bytes,6,opt,name=selected_goarch,json=selectedGoarch,proto3" json:"selected_goarch,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message        string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	Experiments    []*SubmittedExperiment `protobuf:"bytes,9,rep,name=experiments,proto3" json:"experiments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitExperimentBatchResponse) Reset() {
	*x = SubmitExperimentBatchResponse{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitExperimentBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitExperimentBatchResponse) ProtoMessage() {}

func (x *SubmitExperimentBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitExperimentBatchResponse.ProtoReflect.Descriptor instead.
func (*SubmitExperimentBatchResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitExperimentBatchResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitExperimentBatchResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *SubmitExperimentBatchResponse) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *SubmitExperimentBatchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitExperimentBatchResponse) GetSelectedGoos() string {
	if x != nil {
		return x.SelectedGoos
	}
	return ""
}

func (x *SubmitExperimentBatchResponse) GetSelectedGoarch() string {
	if x != nil {
		return x.SelectedGoarch
	}
	return ""
}

func (x *SubmitExperimentBatchResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SubmitExperimentBatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitExperimentBatchResponse) GetExperiments() []*SubmittedExperiment {
	if x != nil {
		return x.Experiments
	}
	return nil
}

type SubmittedExperiment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelHash     string                 `protobuf:"bytes,1,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	ExperimentId  string                 `protobuf:"bytes,2,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmittedExperiment) Reset() {
	*x = SubmittedExperiment{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmittedExperiment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmittedExperiment) ProtoMessage() {}

func (x *SubmittedExperiment) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmittedExperiment.ProtoReflect.Descriptor instead.
func (*SubmittedExperiment) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *SubmittedExperiment) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *SubmittedExperiment) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *SubmittedExperiment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetExperimentBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExperimentBatchRequest) Reset() {
	*x = GetExperimentBatchRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExperimentBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExperimentBatchRequest) ProtoMessage() {}

func (x *GetExperimentBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExperimentBatchRequest.ProtoReflect.Descriptor instead.
func (*GetExperimentBatchRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{5}
}

func (x *GetExperimentBatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type GetExperimentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelHash     string                 `protobuf:"bytes,1,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	ExperimentId  string                 `protobuf:"bytes,2,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExperimentRequest) Reset() {
	*x = GetExperimentRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExperimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExperimentRequest) ProtoMessage() {}

func (x *GetExperimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExperimentRequest.ProtoReflect.Descriptor instead.
func (*GetExperimentRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{6}
}

func (x *GetExperimentRequest) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *GetExperimentRequest) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

type ExperimentBatchStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BatchId             string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	ModelHash           string                 `protobuf:"bytes,2,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	Status              string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TotalExperiments    int32                  `protobuf:"varint,4,opt,name=total_experiments,json=totalExperiments,proto3" json:"total_experiments,omitempty"`
	PendingExperiments  int32                  `protobuf:"varint,5,opt,name=pending_experiments,json=pendingExperiments,proto3" json:"pending_experiments,omitempty"`
	RunningExperiments  int32                  `protobuf:"varint,6,opt,name=running_experiments,json=runningExperiments,proto3" json:"running_experiments,omitempty"`
	FinishedExperiments int32                  `protobuf:"varint,7,opt,name=finished_experiments,json=finishedExperiments,proto3" json:"finished_experiments,omitempty"`
	FailedExperiments   int32                  `protobuf:"varint,8,opt,name=failed_experiments,json=failedExperiments,proto3" json:"failed_experiments,omitempty"`
	CanceledExperiments int32                  `protobuf:"varint,9,opt,name=canceled_experiments,json=canceledExperiments,proto3" json:"canceled_experiments,omitempty"`
	Artifact            *ModelArtifact         `protobuf:"bytes,10,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Experiments         []*v1.ExperimentStatus `protobuf:"bytes,11,rep,name=experiments,proto3" json:"experiments,omitempty"`
	SelectedGoos        string                 `protobuf:"bytes,12,opt,name=selected_goos,json=selectedGoos,proto3" json:"selected_goos,omitempty"`
	SelectedGoarch      string                 `protobuf:"bytes,13,opt,name=selected_goarch,json=selectedGoarch,proto3" json:"selected_goarch,omitempty"`
	ErrorCode           string                 `protobuf:"bytes,14,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message             string                 `protobuf:"bytes,15,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExperimentBatchStatus) Reset() {
	*x = ExperimentBatchStatus{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentBatchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentBatchStatus) ProtoMessage() {}

func (x *ExperimentBatchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentBatchStatus.ProtoReflect.Descriptor instead.
func (*ExperimentBatchStatus) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{7}
}

func (x *ExperimentBatchStatus) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *ExperimentBatchStatus) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *ExperimentBatchStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExperimentBatchStatus) GetTotalExperiments() int32 {
	if x != nil {
		return x.TotalExperiments
	}
	return 0
}

func (x *ExperimentBatchStatus) GetPendingExperiments() int32 {
	if x != nil {
		return x.PendingExperiments
	}
	return 0
}

func (x *ExperimentBatchStatus) GetRunningExperiments() int32 {
	if x != nil {
		return x.RunningExperiments
	}
	return 0
}

func (x *ExperimentBatchStatus) GetFinishedExperiments() int32 {
	if x != nil {
		return x.FinishedExperiments
	}
	return 0
}

func (x *ExperimentBatchStatus) GetFailedExperiments() int32 {
	if x != nil {
		return x.FailedExperiments
	}
	return 0
}

func (x *ExperimentBatchStatus) GetCanceledExperiments() int32 {
	if x != nil {
		return x.CanceledExperiments
	}
	return 0
}

func (x *ExperimentBatchStatus) GetArtifact() *ModelArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *ExperimentBatchStatus) GetExperiments() []*v1.ExperimentStatus {
	if x != nil {
		return x.Experiments
	}
	return nil
}

func (x *ExperimentBatchStatus) GetSelectedGoos() string {
	if x != nil {
		return x.SelectedGoos
	}
	return ""
}

func (x *ExperimentBatchStatus) GetSelectedGoarch() string {
	if x != nil {
		return x.SelectedGoarch
	}
	return ""
}

func (x *ExperimentBatchStatus) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ExperimentBatchStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ModelArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelHash     string                 `protobuf:"bytes,1,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	Goos          string                 `protobuf:"bytes,2,opt,name=goos,proto3" json:"goos,omitempty"`
	Goarch        string                 `protobuf:"bytes,3,opt,name=goarch,proto3" json:"goarch,omitempty"`
	Source        *v1.ArtifactRef        `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Binary        *v1.ArtifactRef        `protobuf:"bytes,5,opt,name=binary,proto3" json:"binary,omitempty"`
	BuildLog      *v1.ArtifactRef        `protobuf:"bytes,6,opt,name=build_log,json=buildLog,proto3" json:"build_log,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,8,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelArtifact) Reset() {
	*x = ModelArtifact{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelArtifact) ProtoMessage() {}

func (x *ModelArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelArtifact.ProtoReflect.Descriptor instead.
func (*ModelArtifact) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{8}
}

func (x *ModelArtifact) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *ModelArtifact) GetGoos() string {
	if x != nil {
		return x.Goos
	}
	return ""
}

func (x *ModelArtifact) GetGoarch() string {
	if x != nil {
		return x.Goarch
	}
	return ""
}

func (x *ModelArtifact) GetSource() *v1.ArtifactRef {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ModelArtifact) GetBinary() *v1.ArtifactRef {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *ModelArtifact) GetBuildLog() *v1.ArtifactRef {
	if x != nil {
		return x.BuildLog
	}
	return nil
}

func (x *ModelArtifact) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ModelArtifact) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ModelArtifact) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *v1.NodeStatus         `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterNodeRequest) GetNode() *v1.NodeStatus {
	if x != nil {
		return x.Node
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterNodeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NodeHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *v1.NodeStatus         `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	SentAtUnixMs  int64                  `protobuf:"varint,2,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHeartbeat) Reset() {
	*x = NodeHeartbeat{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHeartbeat) ProtoMessage() {}

func (x *NodeHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHeartbeat.ProtoReflect.Descriptor instead.
func (*NodeHeartbeat) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{11}
}

func (x *NodeHeartbeat) GetNode() *v1.NodeStatus {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeHeartbeat) GetSentAtUnixMs() int64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportExperimentResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Result        *v1.ExperimentStatus   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportExperimentResultRequest) Reset() {
	*x = ReportExperimentResultRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportExperimentResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportExperimentResultRequest) ProtoMessage() {}

func (x *ReportExperimentResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportExperimentResultRequest.ProtoReflect.Descriptor instead.
func (*ReportExperimentResultRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{13}
}

func (x *ReportExperimentResultRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportExperimentResultRequest) GetResult() *v1.ExperimentStatus {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReportExperimentResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportExperimentResultResponse) Reset() {
	*x = ReportExperimentResultResponse{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportExperimentResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportExperimentResultResponse) ProtoMessage() {}

func (x *ReportExperimentResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportExperimentResultResponse.ProtoReflect.Descriptor instead.
func (*ReportExperimentResultResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{14}
}

func (x *ReportExperimentResultResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReportExperimentResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{15}
}

func (x *ListNodesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*v1.NodeStatus       `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_controlplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{16}
}

func (x *ListNodesResponse) GetNodes() []*v1.NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_controlplane_v1_controlplane_proto protoreflect.FileDescriptor

const file_controlplane_v1_controlplane_proto_rawDesc = "" +
	"\n" +
	"\"controlplane/v1/controlplane.proto\x12\x0fcontrolplane.v1\x1a\x1edispatcher/v1/dispatcher.proto\"\xc3\x02\n" +
	"\x1cSubmitExperimentBatchRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x10\n" +
	"\x03dsl\x18\x02 \x01(\tR\x03dsl\x12!\n" +
	"\fstore_source\x18\x03 \x01(\bR\vstoreSource\x12!\n" +
	"\fstore_binary\x18\x04 \x01(\bR\vstoreBinary\x12*\n" +
	"\x11build_timeout_sec\x18\x05 \x01(\x05R\x0fbuildTimeoutSec\x12?\n" +
	"\x06common\x18\x06 \x01(\v2'.controlplane.v1.ExperimentCommonConfigR\x06common\x12C\n" +
	"\vexperiments\x18\a \x03(\v2!.controlplane.v1.ExperimentParamsR\vexperiments\"\x82\x02\n" +
	"\x16ExperimentCommonConfig\x124\n" +
	"\tstop_rule\x18\x01 \x01(\v2\x17.dispatcher.v1.StopRuleR\bstopRule\x12\x18\n" +
	"\ametrics\x18\x02 \x03(\tR\ametrics\x12\x1f\n" +
	"\vmetric_step\x18\x03 \x01(\x01R\n" +
	"metricStep\x12#\n" +
	"\rstore_metrics\x18\x04 \x01(\bR\fstoreMetrics\x12,\n" +
	"\x12memory_limit_bytes\x18\x05 \x01(\x04R\x10memoryLimitBytes\x12$\n" +
	"\x0erun_timeout_ms\x18\x06 \x01(\x04R\frunTimeoutMs\"i\n" +
	"\x10ExperimentParams\x12#\n" +
	"\rexperiment_id\x18\x01 \x01(\tR\fexperimentId\x120\n" +
	"\bset_vars\x18\x02 \x03(\v2\x15.dispatcher.v1.SetVarR\asetVars\"\xdc\x02\n" +
	"\x1dSubmitExperimentBatchResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x19\n" +
	"\bbatch_id\x18\x02 \x01(\tR\abatchId\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x03 \x01(\tR\tmodelHash\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rselected_goos\x18\x05 \x01(\tR\fselectedGoos\x12'\n" +
	"\x0fselected_goarch\x18\x06 \x01(\tR\x0eselectedGoarch\x12\x1d\n" +
	"\n" +
	"error_code\x18\a \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12F\n" +
	"\vexperiments\x18\t \x03(\v2$.controlplane.v1.SubmittedExperimentR\vexperiments\"q\n" +
	"\x13SubmittedExperiment\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x01 \x01(\tR\tmodelHash\x12#\n" +
	"\rexperiment_id\x18\x02 \x01(\tR\fexperimentId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"6\n" +
	"\x19GetExperimentBatchRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\"Z\n" +
	"\x14GetExperimentRequest\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x01 \x01(\tR\tmodelHash\x12#\n" +
	"\rexperiment_id\x18\x02 \x01(\tR\fexperimentId\"\x93\x05\n" +
	"\x15ExperimentBatchStatus\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x02 \x01(\tR\tmodelHash\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12+\n" +
	"\x11total_experiments\x18\x04 \x01(\x05R\x10totalExperiments\x12/\n" +
	"\x13pending_experiments\x18\x05 \x01(\x05R\x12pendingExperiments\x12/\n" +
	"\x13running_experiments\x18\x06 \x01(\x05R\x12runningExperiments\x121\n" +
	"\x14finished_experiments\x18\a \x01(\x05R\x13finishedExperiments\x12-\n" +
	"\x12failed_experiments\x18\b \x01(\x05R\x11failedExperiments\x121\n" +
	"\x14canceled_experiments\x18\t \x01(\x05R\x13canceledExperiments\x12:\n" +
	"\bartifact\x18\n" +
	" \x01(\v2\x1e.controlplane.v1.ModelArtifactR\bartifact\x12A\n" +
	"\vexperiments\x18\v \x03(\v2\x1f.dispatcher.v1.ExperimentStatusR\vexperiments\x12#\n" +
	"\rselected_goos\x18\f \x01(\tR\fselectedGoos\x12'\n" +
	"\x0fselected_goarch\x18\r \x01(\tR\x0eselectedGoarch\x12\x1d\n" +
	"\n" +
	"error_code\x18\x0e \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x0f \x01(\tR\amessage\"\xcc\x02\n" +
	"\rModelArtifact\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x01 \x01(\tR\tmodelHash\x12\x12\n" +
	"\x04goos\x18\x02 \x01(\tR\x04goos\x12\x16\n" +
	"\x06goarch\x18\x03 \x01(\tR\x06goarch\x122\n" +
	"\x06source\x18\x04 \x01(\v2\x1a.dispatcher.v1.ArtifactRefR\x06source\x122\n" +
	"\x06binary\x18\x05 \x01(\v2\x1a.dispatcher.v1.ArtifactRefR\x06binary\x127\n" +
	"\tbuild_log\x18\x06 \x01(\v2\x1a.dispatcher.v1.ArtifactRefR\bbuildLog\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\b \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\"D\n" +
	"\x13RegisterNodeRequest\x12-\n" +
	"\x04node\x18\x01 \x01(\v2\x19.dispatcher.v1.NodeStatusR\x04node\"L\n" +
	"\x14RegisterNodeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"e\n" +
	"\rNodeHeartbeat\x12-\n" +
	"\x04node\x18\x01 \x01(\v2\x19.dispatcher.v1.NodeStatusR\x04node\x12%\n" +
	"\x0fsent_at_unix_ms\x18\x02 \x01(\x03R\fsentAtUnixMs\"=\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"q\n" +
	"\x1dReportExperimentResultRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x127\n" +
	"\x06result\x18\x02 \x01(\v2\x1f.dispatcher.v1.ExperimentStatusR\x06result\"J\n" +
	"\x1eReportExperimentResultResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\x10ListNodesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"D\n" +
	"\x11ListNodesResponse\x12/\n" +
	"\x05nodes\x18\x01 \x03(\v2\x19.dispatcher.v1.NodeStatusR\x05nodes2\xa4\x03\n" +
	"\x13ControlPlaneService\x12v\n" +
	"\x15SubmitExperimentBatch\x12-.controlplane.v1.SubmitExperimentBatchRequest\x1a..controlplane.v1.SubmitExperimentBatchResponse\x12h\n" +
	"\x12GetExperimentBatch\x12*.controlplane.v1.GetExperimentBatchRequest\x1a&.controlplane.v1.ExperimentBatchStatus\x12W\n" +
	"\rGetExperiment\x12%.controlplane.v1.GetExperimentRequest\x1a\x1f.dispatcher.v1.ExperimentStatus\x12R\n" +
	"\tListNodes\x12!.controlplane.v1.ListNodesRequest\x1a\".controlplane.v1.ListNodesResponse2\xc6\x02\n" +
	"\x17ControlPlaneNodeService\x12[\n" +
	"\fRegisterNode\x12$.controlplane.v1.RegisterNodeRequest\x1a%.controlplane.v1.RegisterNodeResponse\x12S\n" +
	"\rSendHeartbeat\x12\x1e.controlplane.v1.NodeHeartbeat\x1a\".controlplane.v1.HeartbeatResponse\x12y\n" +
	"\x16ReportExperimentResult\x12..controlplane.v1.ReportExperimentResultRequest\x1a/.controlplane.v1.ReportExperimentResultResponseBGZEgithub.com/gulyaev-iv/go-cloud-des/api/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_controlplane_v1_controlplane_proto_rawDescOnce sync.Once
	file_controlplane_v1_controlplane_proto_rawDescData []byte
)

func file_controlplane_v1_controlplane_proto_rawDescGZIP() []byte {
	file_controlplane_v1_controlplane_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_controlplane_proto_rawDesc), len(file_controlplane_v1_controlplane_proto_rawDesc)))
	})
	return file_controlplane_v1_controlplane_proto_rawDescData
}

var file_controlplane_v1_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_controlplane_v1_controlplane_proto_goTypes = []any{
	(*SubmitExperimentBatchRequest)(nil),   // 0: controlplane.v1.SubmitExperimentBatchRequest
	(*ExperimentCommonConfig)(nil),         // 1: controlplane.v1.ExperimentCommonConfig
	(*ExperimentParams)(nil),               // 2: controlplane.v1.ExperimentParams
	(*SubmitExperimentBatchResponse)(nil),  // 3: controlplane.v1.SubmitExperimentBatchResponse
	(*SubmittedExperiment)(nil),            // 4: controlplane.v1.SubmittedExperiment
	(*GetExperimentBatchRequest)(nil),      // 5: controlplane.v1.GetExperimentBatchRequest
	(*GetExperimentRequest)(nil),           // 6: controlplane.v1.GetExperimentRequest
	(*ExperimentBatchStatus)(nil),          // 7: controlplane.v1.ExperimentBatchStatus
	(*ModelArtifact)(nil),                  // 8: controlplane.v1.ModelArtifact
	(*RegisterNodeRequest)(nil),            // 9: controlplane.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),           // 10: controlplane.v1.RegisterNodeResponse
	(*NodeHeartbeat)(nil),                  // 11: controlplane.v1.NodeHeartbeat
	(*HeartbeatResponse)(nil),              // 12: controlplane.v1.HeartbeatResponse
	(*ReportExperimentResultRequest)(nil),  // 13: controlplane.v1.ReportExperimentResultRequest
	(*ReportExperimentResultResponse)(nil), // 14: controlplane.v1.ReportExperimentResultResponse
	(*ListNodesRequest)(nil),               // 15: controlplane.v1.ListNodesRequest
	(*ListNodesResponse)(nil),              // 16: controlplane.v1.ListNodesResponse
	(*v1.StopRule)(nil),                    // 17: dispatcher.v1.StopRule
	(*v1.SetVar)(nil),                      // 18: dispatcher.v1.SetVar
	(*v1.ExperimentStatus)(nil),            // 19: dispatcher.v1.ExperimentStatus
	(*v1.ArtifactRef)(nil),                 // 20: dispatcher.v1.ArtifactRef
	(*v1.NodeStatus)(nil),                  // 21: dispatcher.v1.NodeStatus
}
var file_controlplane_v1_controlplane_proto_depIdxs = []int32{
	1,  // 0: controlplane.v1.SubmitExperimentBatchRequest.common:type_name -> controlplane.v1.ExperimentCommonConfig
	2,  // 1: controlplane.v1.SubmitExperimentBatchRequest.experiments:type_name -> controlplane.v1.ExperimentParams
	17, // 2: controlplane.v1.ExperimentCommonConfig.stop_rule:type_name -> dispatcher.v1.StopRule
	18, // 3: controlplane.v1.ExperimentParams.set_vars:type_name -> dispatcher.v1.SetVar
	4,  // 4: controlplane.v1.SubmitExperimentBatchResponse.experiments:type_name -> controlplane.v1.SubmittedExperiment
	8,  // 5: controlplane.v1.ExperimentBatchStatus.artifact:type_name -> controlplane.v1.ModelArtifact
	19, // 6: controlplane.v1.ExperimentBatchStatus.experiments:type_name -> dispatcher.v1.ExperimentStatus
	20, // 7: controlplane.v1.ModelArtifact.source:type_name -> dispatcher.v1.ArtifactRef
	20, // 8: controlplane.v1.ModelArtifact.binary:type_name -> dispatcher.v1.ArtifactRef
	20, // 9: controlplane.v1.ModelArtifact.build_log:type_name -> dispatcher.v1.ArtifactRef
	21, // 10: controlplane.v1.RegisterNodeRequest.node:type_name -> dispatcher.v1.NodeStatus
	21, // 11: controlplane.v1.NodeHeartbeat.node:type_name -> dispatcher.v1.NodeStatus
	19, // 12: controlplane.v1.ReportExperimentResultRequest.result:type_name -> dispatcher.v1.ExperimentStatus
	21, // 13: controlplane.v1.ListNodesResponse.nodes:type_name -> dispatcher.v1.NodeStatus
	0,  // 14: controlplane.v1.ControlPlaneService.SubmitExperimentBatch:input_type -> controlplane.v1.SubmitExperimentBatchRequest
	5,  // 15: controlplane.v1.ControlPlaneService.GetExperimentBatch:input_type -> controlplane.v1.GetExperimentBatchRequest
	6,  // 16: controlplane.v1.ControlPlaneService.GetExperiment:input_type -> controlplane.v1.GetExperimentRequest
	15, // 17: controlplane.v1.ControlPlaneService.ListNodes:input_type -> controlplane.v1.ListNodesRequest
	9,  // 18: controlplane.v1.ControlPlaneNodeService.RegisterNode:input_type -> controlplane.v1.RegisterNodeRequest
	11, // 19: controlplane.v1.ControlPlaneNodeService.SendHeartbeat:input_type -> controlplane.v1.NodeHeartbeat
	13, // 20: controlplane.v1.ControlPlaneNodeService.ReportExperimentResult:input_type -> controlplane.v1.ReportExperimentResultRequest
	3,  // 21: controlplane.v1.ControlPlaneService.SubmitExperimentBatch:output_type -> controlplane.v1.SubmitExperimentBatchResponse
	7,  // 22: controlplane.v1.ControlPlaneService.GetExperimentBatch:output_type -> controlplane.v1.ExperimentBatchStatus
	19, // 23: controlplane.v1.ControlPlaneService.GetExperiment:output_type -> dispatcher.v1.ExperimentStatus
	16, // 24: controlplane.v1.ControlPlaneService.ListNodes:output_type -> controlplane.v1.ListNodesResponse
	10, // 25: controlplane.v1.ControlPlaneNodeService.RegisterNode:output_type -> controlplane.v1.RegisterNodeResponse
	12, // 26: controlplane.v1.ControlPlaneNodeService.SendHeartbeat:output_type -> controlplane.v1.HeartbeatResponse
	14, // 27: controlplane.v1.ControlPlaneNodeService.ReportExperimentResult:output_type -> controlplane.v1.ReportExperimentResultResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_controlplane_v1_controlplane_proto_init() }
func file_controlplane_v1_controlplane_proto_init() {
	if File_controlplane_v1_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_controlplane_proto_rawDesc), len(file_controlplane_v1_controlplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_controlplane_v1_controlplane_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_controlplane_proto_depIdxs,
		MessageInfos:      file_controlplane_v1_controlplane_proto_msgTypes,
	}.Build()
	File_controlplane_v1_controlplane_proto = out.File
	file_controlplane_v1_controlplane_proto_goTypes = nil
	file_controlplane_v1_controlplane_proto_depIdxs = nil
}
