// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: controlplane/v1/controlplane.proto

package controlplanev1

import (
	context "context"
	v1 "github.com/gulyaev-iv/go-cloud-des/api/dispatcher/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneService_SubmitExperimentBatch_FullMethodName = "/controlplane.v1.ControlPlaneService/SubmitExperimentBatch"
	ControlPlaneService_GetExperimentBatch_FullMethodName    = "/controlplane.v1.ControlPlaneService/GetExperimentBatch"
	ControlPlaneService_GetExperiment_FullMethodName         = "/controlplane.v1.ControlPlaneService/GetExperiment"
	ControlPlaneService_CancelExperiment_FullMethodName      = "/controlplane.v1.ControlPlaneService/CancelExperiment"
	ControlPlaneService_ListNodes_FullMethodName             = "/controlplane.v1.ControlPlaneService/ListNodes"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneServiceClient interface {
	SubmitExperimentBatch(ctx context.Context, in *SubmitExperimentBatchRequest, opts ...grpc.CallOption) (*SubmitExperimentBatchResponse, error)
	GetExperimentBatch(ctx context.Context, in *GetExperimentBatchRequest, opts ...grpc.CallOption) (*ExperimentBatchStatus, error)
	GetExperiment(ctx context.Context, in *GetExperimentRequest, opts ...grpc.CallOption) (*v1.ExperimentStatus, error)
	CancelExperiment(ctx context.Context, in *CancelExperimentRequest, opts ...grpc.CallOption) (*CancelExperimentResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) SubmitExperimentBatch(ctx context.Context, in *SubmitExperimentBatchRequest, opts ...grpc.CallOption) (*SubmitExperimentBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitExperimentBatchResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_SubmitExperimentBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetExperimentBatch(ctx context.Context, in *GetExperimentBatchRequest, opts ...grpc.CallOption) (*ExperimentBatchStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExperimentBatchStatus)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetExperimentBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetExperiment(ctx context.Context, in *GetExperimentRequest, opts ...grpc.CallOption) (*v1.ExperimentStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ExperimentStatus)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetExperiment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) CancelExperiment(ctx context.Context, in *CancelExperimentRequest, opts ...grpc.CallOption) (*CancelExperimentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelExperimentResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_CancelExperiment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
type ControlPlaneServiceServer interface {
	SubmitExperimentBatch(context.Context, *SubmitExperimentBatchRequest) (*SubmitExperimentBatchResponse, error)
	GetExperimentBatch(context.Context, *GetExperimentBatchRequest) (*ExperimentBatchStatus, error)
	GetExperiment(context.Context, *GetExperimentRequest) (*v1.ExperimentStatus, error)
	CancelExperiment(context.Context, *CancelExperimentRequest) (*CancelExperimentResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) SubmitExperimentBatch(context.Context, *SubmitExperimentBatchRequest) (*SubmitExperimentBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitExperimentBatch not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetExperimentBatch(context.Context, *GetExperimentBatchRequest) (*ExperimentBatchStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExperimentBatch not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetExperiment(context.Context, *GetExperimentRequest) (*v1.ExperimentStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExperiment not implemented")
}
func (UnimplementedControlPlaneServiceServer) CancelExperiment(context.Context, *CancelExperimentRequest) (*CancelExperimentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelExperiment not implemented")
}
func (UnimplementedControlPlaneServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_SubmitExperimentBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitExperimentBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).SubmitExperimentBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_SubmitExperimentBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).SubmitExperimentBatch(ctx, req.(*SubmitExperimentBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetExperimentBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExperimentBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetExperimentBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetExperimentBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetExperimentBatch(ctx, req.(*GetExperimentBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetExperiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExperimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetExperiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetExperiment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetExperiment(ctx, req.(*GetExperimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_CancelExperiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelExperimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).CancelExperiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_CancelExperiment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).CancelExperiment(ctx, req.(*CancelExperimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlplane.v1.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitExperimentBatch",
			Handler:    _ControlPlaneService_SubmitExperimentBatch_Handler,
		},
		{
			MethodName: "GetExperimentBatch",
			Handler:    _ControlPlaneService_GetExperimentBatch_Handler,
		},
		{
			MethodName: "GetExperiment",
			Handler:    _ControlPlaneService_GetExperiment_Handler,
		},
		{
			MethodName: "CancelExperiment",
			Handler:    _ControlPlaneService_CancelExperiment_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _ControlPlaneService_ListNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controlplane/v1/controlplane.proto",
}

const (
	ControlPlaneNodeService_RegisterNode_FullMethodName           = "/controlplane.v1.ControlPlaneNodeService/RegisterNode"
	ControlPlaneNodeService_SendHeartbeat_FullMethodName          = "/controlplane.v1.ControlPlaneNodeService/SendHeartbeat"
	ControlPlaneNodeService_ReportExperimentResult_FullMethodName = "/controlplane.v1.ControlPlaneNodeService/ReportExperimentResult"
)

// ControlPlaneNodeServiceClient is the client API for ControlPlaneNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneNodeServiceClient interface {
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	SendHeartbeat(ctx context.Context, in *NodeHeartbeat, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ReportExperimentResult(ctx context.Context, in *ReportExperimentResultRequest, opts ...grpc.CallOption) (*ReportExperimentResultResponse, error)
}

type controlPlaneNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneNodeServiceClient(cc grpc.ClientConnInterface) ControlPlaneNodeServiceClient {
	return &controlPlaneNodeServiceClient{cc}
}

func (c *controlPlaneNodeServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, ControlPlaneNodeService_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneNodeServiceClient) SendHeartbeat(ctx context.Context, in *NodeHeartbeat, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControlPlaneNodeService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneNodeServiceClient) ReportExperimentResult(ctx context.Context, in *ReportExperimentResultRequest, opts ...grpc.CallOption) (*ReportExperimentResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportExperimentResultResponse)
	err := c.cc.Invoke(ctx, ControlPlaneNodeService_ReportExperimentResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneNodeServiceServer is the server API for ControlPlaneNodeService service.
// All implementations must embed UnimplementedControlPlaneNodeServiceServer
// for forward compatibility.
type ControlPlaneNodeServiceServer interface {
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	SendHeartbeat(context.Context, *NodeHeartbeat) (*HeartbeatResponse, error)
	ReportExperimentResult(context.Context, *ReportExperimentResultRequest) (*ReportExperimentResultResponse, error)
	mustEmbedUnimplementedControlPlaneNodeServiceServer()
}

// UnimplementedControlPlaneNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneNodeServiceServer struct{}

func (UnimplementedControlPlaneNodeServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedControlPlaneNodeServiceServer) SendHeartbeat(context.Context, *NodeHeartbeat) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedControlPlaneNodeServiceServer) ReportExperimentResult(context.Context, *ReportExperimentResultRequest) (*ReportExperimentResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportExperimentResult not implemented")
}
func (UnimplementedControlPlaneNodeServiceServer) mustEmbedUnimplementedControlPlaneNodeServiceServer() {
}
func (UnimplementedControlPlaneNodeServiceServer) testEmbeddedByValue() {}

// UnsafeControlPlaneNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneNodeServiceServer will
// result in compilation errors.
type UnsafeControlPlaneNodeServiceServer interface {
	mustEmbedUnimplementedControlPlaneNodeServiceServer()
}

func RegisterControlPlaneNodeServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneNodeServiceServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneNodeService_ServiceDesc, srv)
}

func _ControlPlaneNodeService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneNodeServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneNodeService_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneNodeServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneNodeService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneNodeServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneNodeService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneNodeServiceServer).SendHeartbeat(ctx, req.(*NodeHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneNodeService_ReportExperimentResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportExperimentResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneNodeServiceServer).ReportExperimentResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneNodeService_ReportExperimentResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneNodeServiceServer).ReportExperimentResult(ctx, req.(*ReportExperimentResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneNodeService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlplane.v1.ControlPlaneNodeService",
	HandlerType: (*ControlPlaneNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _ControlPlaneNodeService_RegisterNode_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _ControlPlaneNodeService_SendHeartbeat_Handler,
		},
		{
			MethodName: "ReportExperimentResult",
			Handler:    _ControlPlaneNodeService_ReportExperimentResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controlplane/v1/controlplane.proto",
}
