// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: dispatcher/v1/dispatcher.proto

package dispatcherv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryArtifact) Reset() {
	*x = BinaryArtifact{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryArtifact) ProtoMessage() {}

func (x *BinaryArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryArtifact.ProtoReflect.Descriptor instead.
func (*BinaryArtifact) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{0}
}

func (x *BinaryArtifact) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BinaryArtifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ArtifactRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ArtifactRef) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ArtifactRef) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type SetVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVar) Reset() {
	*x = SetVar{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVar) ProtoMessage() {}

func (x *SetVar) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVar.ProtoReflect.Descriptor instead.
func (*SetVar) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{2}
}

func (x *SetVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StopRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          string                 `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Right         string                 `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRule) Reset() {
	*x = StopRule{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRule) ProtoMessage() {}

func (x *StopRule) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRule.ProtoReflect.Descriptor instead.
func (*StopRule) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{3}
}

func (x *StopRule) GetLeft() string {
	if x != nil {
		return x.Left
	}
	return ""
}

func (x *StopRule) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *StopRule) GetRight() string {
	if x != nil {
		return x.Right
	}
	return ""
}

type StartExperimentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModelHash        string                 `protobuf:"bytes,1,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	ExperimentId     string                 `protobuf:"bytes,2,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	Binary           *BinaryArtifact        `protobuf:"bytes,3,opt,name=binary,proto3" json:"binary,omitempty"`
	SetVars          []*SetVar              `protobuf:"bytes,4,rep,name=set_vars,json=setVars,proto3" json:"set_vars,omitempty"`
	StopRule         *StopRule              `protobuf:"bytes,5,opt,name=stop_rule,json=stopRule,proto3" json:"stop_rule,omitempty"`
	Metrics          []string               `protobuf:"bytes,6,rep,name=metrics,proto3" json:"metrics,omitempty"`
	MetricStep       float64                `protobuf:"fixed64,7,opt,name=metric_step,json=metricStep,proto3" json:"metric_step,omitempty"`
	StoreMetrics     bool                   `protobuf:"varint,8,opt,name=store_metrics,json=storeMetrics,proto3" json:"store_metrics,omitempty"`
	MemoryLimitBytes uint64                 `protobuf:"varint,9,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	RunTimeoutMs     uint64                 `protobuf:"varint,10,opt,name=run_timeout_ms,json=runTimeoutMs,proto3" json:"run_timeout_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartExperimentRequest) Reset() {
	*x = StartExperimentRequest{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartExperimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartExperimentRequest) ProtoMessage() {}

func (x *StartExperimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartExperimentRequest.ProtoReflect.Descriptor instead.
func (*StartExperimentRequest) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{4}
}

func (x *StartExperimentRequest) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *StartExperimentRequest) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *StartExperimentRequest) GetBinary() *BinaryArtifact {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *StartExperimentRequest) GetSetVars() []*SetVar {
	if x != nil {
		return x.SetVars
	}
	return nil
}

func (x *StartExperimentRequest) GetStopRule() *StopRule {
	if x != nil {
		return x.StopRule
	}
	return nil
}

func (x *StartExperimentRequest) GetMetrics() []string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *StartExperimentRequest) GetMetricStep() float64 {
	if x != nil {
		return x.MetricStep
	}
	return 0
}

func (x *StartExperimentRequest) GetStoreMetrics() bool {
	if x != nil {
		return x.StoreMetrics
	}
	return false
}

func (x *StartExperimentRequest) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *StartExperimentRequest) GetRunTimeoutMs() uint64 {
	if x != nil {
		return x.RunTimeoutMs
	}
	return 0
}

type StartExperimentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ModelHash     string                 `protobuf:"bytes,2,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	ExperimentId  string                 `protobuf:"bytes,3,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartExperimentResponse) Reset() {
	*x = StartExperimentResponse{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartExperimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartExperimentResponse) ProtoMessage() {}

func (x *StartExperimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartExperimentResponse.ProtoReflect.Descriptor instead.
func (*StartExperimentResponse) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{5}
}

func (x *StartExperimentResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StartExperimentResponse) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *StartExperimentResponse) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *StartExperimentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartExperimentResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *StartExperimentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopExperimentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelHash     string                 `protobuf:"bytes,1,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	ExperimentId  string                 `protobuf:"bytes,2,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopExperimentRequest) Reset() {
	*x = StopExperimentRequest{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopExperimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopExperimentRequest) ProtoMessage() {}

func (x *StopExperimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopExperimentRequest.ProtoReflect.Descriptor instead.
func (*StopExperimentRequest) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{6}
}

func (x *StopExperimentRequest) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *StopExperimentRequest) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

type StopExperimentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"`
	ModelHash     string                 `protobuf:"bytes,2,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	ExperimentId  string                 `protobuf:"bytes,3,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopExperimentResponse) Reset() {
	*x = StopExperimentResponse{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopExperimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopExperimentResponse) ProtoMessage() {}

func (x *StopExperimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopExperimentResponse.ProtoReflect.Descriptor instead.
func (*StopExperimentResponse) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{7}
}

func (x *StopExperimentResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

func (x *StopExperimentResponse) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *StopExperimentResponse) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *StopExperimentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StopExperimentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetExperimentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelHash     string                 `protobuf:"bytes,1,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	ExperimentId  string                 `protobuf:"bytes,2,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExperimentRequest) Reset() {
	*x = GetExperimentRequest{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExperimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExperimentRequest) ProtoMessage() {}

func (x *GetExperimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExperimentRequest.ProtoReflect.Descriptor instead.
func (*GetExperimentRequest) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{8}
}

func (x *GetExperimentRequest) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *GetExperimentRequest) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

type ExperimentStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModelHash        string                 `protobuf:"bytes,1,opt,name=model_hash,json=modelHash,proto3" json:"model_hash,omitempty"`
	ExperimentId     string                 `protobuf:"bytes,2,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	FinishReason     string                 `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	ExitCode         int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FinalMetrics     map[string]string      `protobuf:"bytes,7,rep,name=final_metrics,json=finalMetrics,proto3" json:"final_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StatCount        uint64                 `protobuf:"varint,8,opt,name=stat_count,json=statCount,proto3" json:"stat_count,omitempty"`
	MetricsFileRows  uint64                 `protobuf:"varint,9,opt,name=metrics_file_rows,json=metricsFileRows,proto3" json:"metrics_file_rows,omitempty"`
	MetricsArtifact  *ArtifactRef           `protobuf:"bytes,10,opt,name=metrics_artifact,json=metricsArtifact,proto3" json:"metrics_artifact,omitempty"`
	StartedAtUnixMs  int64                  `protobuf:"varint,11,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	FinishedAtUnixMs int64                  `protobuf:"varint,12,opt,name=finished_at_unix_ms,json=finishedAtUnixMs,proto3" json:"finished_at_unix_ms,omitempty"`
	DurationMs       int64                  `protobuf:"varint,13,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	MemoryLimitBytes uint64                 `protobuf:"varint,14,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	PeakMemoryBytes  uint64                 `protobuf:"varint,15,opt,name=peak_memory_bytes,json=peakMemoryBytes,proto3" json:"peak_memory_bytes,omitempty"`
	StderrTail       string                 `protobuf:"bytes,16,opt,name=stderr_tail,json=stderrTail,proto3" json:"stderr_tail,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExperimentStatus) Reset() {
	*x = ExperimentStatus{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentStatus) ProtoMessage() {}

func (x *ExperimentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentStatus.ProtoReflect.Descriptor instead.
func (*ExperimentStatus) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{9}
}

func (x *ExperimentStatus) GetModelHash() string {
	if x != nil {
		return x.ModelHash
	}
	return ""
}

func (x *ExperimentStatus) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *ExperimentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExperimentStatus) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ExperimentStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExperimentStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExperimentStatus) GetFinalMetrics() map[string]string {
	if x != nil {
		return x.FinalMetrics
	}
	return nil
}

func (x *ExperimentStatus) GetStatCount() uint64 {
	if x != nil {
		return x.StatCount
	}
	return 0
}

func (x *ExperimentStatus) GetMetricsFileRows() uint64 {
	if x != nil {
		return x.MetricsFileRows
	}
	return 0
}

func (x *ExperimentStatus) GetMetricsArtifact() *ArtifactRef {
	if x != nil {
		return x.MetricsArtifact
	}
	return nil
}

func (x *ExperimentStatus) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *ExperimentStatus) GetFinishedAtUnixMs() int64 {
	if x != nil {
		return x.FinishedAtUnixMs
	}
	return 0
}

func (x *ExperimentStatus) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExperimentStatus) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *ExperimentStatus) GetPeakMemoryBytes() uint64 {
	if x != nil {
		return x.PeakMemoryBytes
	}
	return 0
}

func (x *ExperimentStatus) GetStderrTail() string {
	if x != nil {
		return x.StderrTail
	}
	return ""
}

type ListExperimentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExperimentsRequest) Reset() {
	*x = ListExperimentsRequest{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExperimentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExperimentsRequest) ProtoMessage() {}

func (x *ListExperimentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExperimentsRequest.ProtoReflect.Descriptor instead.
func (*ListExperimentsRequest) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{10}
}

func (x *ListExperimentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListExperimentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Experiments   []*ExperimentStatus    `protobuf:"bytes,1,rep,name=experiments,proto3" json:"experiments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExperimentsResponse) Reset() {
	*x = ListExperimentsResponse{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExperimentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExperimentsResponse) ProtoMessage() {}

func (x *ListExperimentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExperimentsResponse.ProtoReflect.Descriptor instead.
func (*ListExperimentsResponse) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{11}
}

func (x *ListExperimentsResponse) GetExperiments() []*ExperimentStatus {
	if x != nil {
		return x.Experiments
	}
	return nil
}

type GetNodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatusRequest) Reset() {
	*x = GetNodeStatusRequest{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatusRequest) ProtoMessage() {}

func (x *GetNodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{12}
}

type NodeStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NodeId              string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address             string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RuntimeGoos         string                 `protobuf:"bytes,3,opt,name=runtime_goos,json=runtimeGoos,proto3" json:"runtime_goos,omitempty"`
	RuntimeGoarch       string                 `protobuf:"bytes,4,opt,name=runtime_goarch,json=runtimeGoarch,proto3" json:"runtime_goarch,omitempty"`
	TotalSlots          uint64                 `protobuf:"varint,5,opt,name=total_slots,json=totalSlots,proto3" json:"total_slots,omitempty"`
	UsedSlots           uint64                 `protobuf:"varint,6,opt,name=used_slots,json=usedSlots,proto3" json:"used_slots,omitempty"`
	TotalMemoryBytes    uint64                 `protobuf:"varint,7,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"`
	ReservedMemoryBytes uint64                 `protobuf:"varint,8,opt,name=reserved_memory_bytes,json=reservedMemoryBytes,proto3" json:"reserved_memory_bytes,omitempty"`
	ActiveExperiments   uint64                 `protobuf:"varint,9,opt,name=active_experiments,json=activeExperiments,proto3" json:"active_experiments,omitempty"`
	CachedModels        uint64                 `protobuf:"varint,10,opt,name=cached_models,json=cachedModels,proto3" json:"cached_models,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dispatcher_v1_dispatcher_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_dispatcher_v1_dispatcher_proto_rawDescGZIP(), []int{13}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeStatus) GetRuntimeGoos() string {
	if x != nil {
		return x.RuntimeGoos
	}
	return ""
}

func (x *NodeStatus) GetRuntimeGoarch() string {
	if x != nil {
		return x.RuntimeGoarch
	}
	return ""
}

func (x *NodeStatus) GetTotalSlots() uint64 {
	if x != nil {
		return x.TotalSlots
	}
	return 0
}

func (x *NodeStatus) GetUsedSlots() uint64 {
	if x != nil {
		return x.UsedSlots
	}
	return 0
}

func (x *NodeStatus) GetTotalMemoryBytes() uint64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

func (x *NodeStatus) GetReservedMemoryBytes() uint64 {
	if x != nil {
		return x.ReservedMemoryBytes
	}
	return 0
}

func (x *NodeStatus) GetActiveExperiments() uint64 {
	if x != nil {
		return x.ActiveExperiments
	}
	return 0
}

func (x *NodeStatus) GetCachedModels() uint64 {
	if x != nil {
		return x.CachedModels
	}
	return 0
}

var File_dispatcher_v1_dispatcher_proto protoreflect.FileDescriptor

const file_dispatcher_v1_dispatcher_proto_rawDesc = "" +
	"\n" +
	"\x1edispatcher/v1/dispatcher.proto\x12\rdispatcher.v1\":\n" +
	"\x0eBinaryArtifact\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"n\n" +
	"\vArtifactRef\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"2\n" +
	"\x06SetVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"D\n" +
	"\bStopRule\x12\x12\n" +
	"\x04left\x18\x01 \x01(\tR\x04left\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x14\n" +
	"\x05right\x18\x03 \x01(\tR\x05right\"\xaf\x03\n" +
	"\x16StartExperimentRequest\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x01 \x01(\tR\tmodelHash\x12#\n" +
	"\rexperiment_id\x18\x02 \x01(\tR\fexperimentId\x125\n" +
	"\x06binary\x18\x03 \x01(\v2\x1d.dispatcher.v1.BinaryArtifactR\x06binary\x120\n" +
	"\bset_vars\x18\x04 \x03(\v2\x15.dispatcher.v1.SetVarR\asetVars\x124\n" +
	"\tstop_rule\x18\x05 \x01(\v2\x17.dispatcher.v1.StopRuleR\bstopRule\x12\x18\n" +
	"\ametrics\x18\x06 \x03(\tR\ametrics\x12\x1f\n" +
	"\vmetric_step\x18\a \x01(\x01R\n" +
	"metricStep\x12#\n" +
	"\rstore_metrics\x18\b \x01(\bR\fstoreMetrics\x12,\n" +
	"\x12memory_limit_bytes\x18\t \x01(\x04R\x10memoryLimitBytes\x12$\n" +
	"\x0erun_timeout_ms\x18\n" +
	" \x01(\x04R\frunTimeoutMs\"\xca\x01\n" +
	"\x17StartExperimentResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x02 \x01(\tR\tmodelHash\x12#\n" +
	"\rexperiment_id\x18\x03 \x01(\tR\fexperimentId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"[\n" +
	"\x15StopExperimentRequest\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x01 \x01(\tR\tmodelHash\x12#\n" +
	"\rexperiment_id\x18\x02 \x01(\tR\fexperimentId\"\xa8\x01\n" +
	"\x16StopExperimentResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x02 \x01(\tR\tmodelHash\x12#\n" +
	"\rexperiment_id\x18\x03 \x01(\tR\fexperimentId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"Z\n" +
	"\x14GetExperimentRequest\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x01 \x01(\tR\tmodelHash\x12#\n" +
	"\rexperiment_id\x18\x02 \x01(\tR\fexperimentId\"\xf8\x05\n" +
	"\x10ExperimentStatus\x12\x1d\n" +
	"\n" +
	"model_hash\x18\x01 \x01(\tR\tmodelHash\x12#\n" +
	"\rexperiment_id\x18\x02 \x01(\tR\fexperimentId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rfinish_reason\x18\x04 \x01(\tR\ffinishReason\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12V\n" +
	"\rfinal_metrics\x18\a \x03(\v21.dispatcher.v1.ExperimentStatus.FinalMetricsEntryR\ffinalMetrics\x12\x1d\n" +
	"\n" +
	"stat_count\x18\b \x01(\x04R\tstatCount\x12*\n" +
	"\x11metrics_file_rows\x18\t \x01(\x04R\x0fmetricsFileRows\x12E\n" +
	"\x10metrics_artifact\x18\n" +
	" \x01(\v2\x1a.dispatcher.v1.ArtifactRefR\x0fmetricsArtifact\x12+\n" +
	"\x12started_at_unix_ms\x18\v \x01(\x03R\x0fstartedAtUnixMs\x12-\n" +
	"\x13finished_at_unix_ms\x18\f \x01(\x03R\x10finishedAtUnixMs\x12\x1f\n" +
	"\vduration_ms\x18\r \x01(\x03R\n" +
	"durationMs\x12,\n" +
	"\x12memory_limit_bytes\x18\x0e \x01(\x04R\x10memoryLimitBytes\x12*\n" +
	"\x11peak_memory_bytes\x18\x0f \x01(\x04R\x0fpeakMemoryBytes\x12\x1f\n" +
	"\vstderr_tail\x18\x10 \x01(\tR\n" +
	"stderrTail\x1a?\n" +
	"\x11FinalMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x16ListExperimentsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\\\n" +
	"\x17ListExperimentsResponse\x12A\n" +
	"\vexperiments\x18\x01 \x03(\v2\x1f.dispatcher.v1.ExperimentStatusR\vexperiments\"\x16\n" +
	"\x14GetNodeStatusRequest\"\xff\x02\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12!\n" +
	"\fruntime_goos\x18\x03 \x01(\tR\vruntimeGoos\x12%\n" +
	"\x0eruntime_goarch\x18\x04 \x01(\tR\rruntimeGoarch\x12\x1f\n" +
	"\vtotal_slots\x18\x05 \x01(\x04R\n" +
	"totalSlots\x12\x1d\n" +
	"\n" +
	"used_slots\x18\x06 \x01(\x04R\tusedSlots\x12,\n" +
	"\x12total_memory_bytes\x18\a \x01(\x04R\x10totalMemoryBytes\x122\n" +
	"\x15reserved_memory_bytes\x18\b \x01(\x04R\x13reservedMemoryBytes\x12-\n" +
	"\x12active_experiments\x18\t \x01(\x04R\x11activeExperiments\x12#\n" +
	"\rcached_models\x18\n" +
	" \x01(\x04R\fcachedModels2\xde\x03\n" +
	"\x11DispatcherService\x12`\n" +
	"\x0fStartExperiment\x12%.dispatcher.v1.StartExperimentRequest\x1a&.dispatcher.v1.StartExperimentResponse\x12]\n" +
	"\x0eStopExperiment\x12$.dispatcher.v1.StopExperimentRequest\x1a%.dispatcher.v1.StopExperimentResponse\x12U\n" +
	"\rGetExperiment\x12#.dispatcher.v1.GetExperimentRequest\x1a\x1f.dispatcher.v1.ExperimentStatus\x12`\n" +
	"\x0fListExperiments\x12%.dispatcher.v1.ListExperimentsRequest\x1a&.dispatcher.v1.ListExperimentsResponse\x12O\n" +
	"\rGetNodeStatus\x12#.dispatcher.v1.GetNodeStatusRequest\x1a\x19.dispatcher.v1.NodeStatusBCZAgithub.com/gulyaev-iv/go-cloud-des/api/dispatcher/v1;dispatcherv1b\x06proto3"

var (
	file_dispatcher_v1_dispatcher_proto_rawDescOnce sync.Once
	file_dispatcher_v1_dispatcher_proto_rawDescData []byte
)

func file_dispatcher_v1_dispatcher_proto_rawDescGZIP() []byte {
	file_dispatcher_v1_dispatcher_proto_rawDescOnce.Do(func() {
		file_dispatcher_v1_dispatcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dispatcher_v1_dispatcher_proto_rawDesc), len(file_dispatcher_v1_dispatcher_proto_rawDesc)))
	})
	return file_dispatcher_v1_dispatcher_proto_rawDescData
}

var file_dispatcher_v1_dispatcher_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_dispatcher_v1_dispatcher_proto_goTypes = []any{
	(*BinaryArtifact)(nil),          // 0: dispatcher.v1.BinaryArtifact
	(*ArtifactRef)(nil),             // 1: dispatcher.v1.ArtifactRef
	(*SetVar)(nil),                  // 2: dispatcher.v1.SetVar
	(*StopRule)(nil),                // 3: dispatcher.v1.StopRule
	(*StartExperimentRequest)(nil),  // 4: dispatcher.v1.StartExperimentRequest
	(*StartExperimentResponse)(nil), // 5: dispatcher.v1.StartExperimentResponse
	(*StopExperimentRequest)(nil),   // 6: dispatcher.v1.StopExperimentRequest
	(*StopExperimentResponse)(nil),  // 7: dispatcher.v1.StopExperimentResponse
	(*GetExperimentRequest)(nil),    // 8: dispatcher.v1.GetExperimentRequest
	(*ExperimentStatus)(nil),        // 9: dispatcher.v1.ExperimentStatus
	(*ListExperimentsRequest)(nil),  // 10: dispatcher.v1.ListExperimentsRequest
	(*ListExperimentsResponse)(nil), // 11: dispatcher.v1.ListExperimentsResponse
	(*GetNodeStatusRequest)(nil),    // 12: dispatcher.v1.GetNodeStatusRequest
	(*NodeStatus)(nil),              // 13: dispatcher.v1.NodeStatus
	nil,                             // 14: dispatcher.v1.ExperimentStatus.FinalMetricsEntry
}
var file_dispatcher_v1_dispatcher_proto_depIdxs = []int32{
	0,  // 0: dispatcher.v1.StartExperimentRequest.binary:type_name -> dispatcher.v1.BinaryArtifact
	2,  // 1: dispatcher.v1.StartExperimentRequest.set_vars:type_name -> dispatcher.v1.SetVar
	3,  // 2: dispatcher.v1.StartExperimentRequest.stop_rule:type_name -> dispatcher.v1.StopRule
	14, // 3: dispatcher.v1.ExperimentStatus.final_metrics:type_name -> dispatcher.v1.ExperimentStatus.FinalMetricsEntry
	1,  // 4: dispatcher.v1.ExperimentStatus.metrics_artifact:type_name -> dispatcher.v1.ArtifactRef
	9,  // 5: dispatcher.v1.ListExperimentsResponse.experiments:type_name -> dispatcher.v1.ExperimentStatus
	4,  // 6: dispatcher.v1.DispatcherService.StartExperiment:input_type -> dispatcher.v1.StartExperimentRequest
	6,  // 7: dispatcher.v1.DispatcherService.StopExperiment:input_type -> dispatcher.v1.StopExperimentRequest
	8,  // 8: dispatcher.v1.DispatcherService.GetExperiment:input_type -> dispatcher.v1.GetExperimentRequest
	10, // 9: dispatcher.v1.DispatcherService.ListExperiments:input_type -> dispatcher.v1.ListExperimentsRequest
	12, // 10: dispatcher.v1.DispatcherService.GetNodeStatus:input_type -> dispatcher.v1.GetNodeStatusRequest
	5,  // 11: dispatcher.v1.DispatcherService.StartExperiment:output_type -> dispatcher.v1.StartExperimentResponse
	7,  // 12: dispatcher.v1.DispatcherService.StopExperiment:output_type -> dispatcher.v1.StopExperimentResponse
	9,  // 13: dispatcher.v1.DispatcherService.GetExperiment:output_type -> dispatcher.v1.ExperimentStatus
	11, // 14: dispatcher.v1.DispatcherService.ListExperiments:output_type -> dispatcher.v1.ListExperimentsResponse
	13, // 15: dispatcher.v1.DispatcherService.GetNodeStatus:output_type -> dispatcher.v1.NodeStatus
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_dispatcher_v1_dispatcher_proto_init() }
func file_dispatcher_v1_dispatcher_proto_init() {
	if File_dispatcher_v1_dispatcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dispatcher_v1_dispatcher_proto_rawDesc), len(file_dispatcher_v1_dispatcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dispatcher_v1_dispatcher_proto_goTypes,
		DependencyIndexes: file_dispatcher_v1_dispatcher_proto_depIdxs,
		MessageInfos:      file_dispatcher_v1_dispatcher_proto_msgTypes,
	}.Build()
	File_dispatcher_v1_dispatcher_proto = out.File
	file_dispatcher_v1_dispatcher_proto_goTypes = nil
	file_dispatcher_v1_dispatcher_proto_depIdxs = nil
}
